language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- echo "Running Tests with 'pytest'"
- pytest
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: davydany
  on:
    all_branches: true
    python:
      - 3.6
  password:
    secure: LOVG+O3wg9uIj35G5UUCJMob53PrD5CqFCVpo1pMpU5MTmbOrqyIyCOpzzGC/sEuqYd3BsuHMttTTOhi1GZqlnMZb3iXFOL/9C7rjHYxf0514QjZK/FSwInAIyL+8BPD8RusdXgm2BLKGtvyF39fchLtYFKgt3CqUPZOYgzP1PoQE8UjTpxEwAjOFbEXMirYNQtJi6kJYvL2RuCjzsoIkoZ/hwa69bqQcOwkO1PjKGZqZN3CEA0nJ8YAA40s4V05w66WH1wV0cmcmFr+MyMi9PTHIczpKoH/zW5uriS7hgWancSPbov7YVJ9P6ERnlIqA0K5SHIcoduC7KCCE/R2hS0nvwg3qgqKfgsHCd4GyzxurebLKHv1kk25lFpIQAYdgcbk8UH33JcF77Hg5Nyxw9liDsPNEeopumua6FMLFUmqcEnmGsZfXhnLpXh689zW5BR9Cu9V9qiACcpKo7ZOjaqbrSD6k2ZwT/S/THR/5GDrWSv4z5fi4fum4eOTVXpsiNV/lfzkF2JOT8Ap79KqtVtq28F7BUsq/5jRGAC7Cyy8GjkcTfoA+Evc/xLttzMgZCudA0yJQ6d7hapyvS458K3TQtlzF586BxABpcLgXwLluYtv6v0jB6kQkvoEEN8niFNiW/auMGnLUIHpc5WVlEdKTJvKUSVc+aOyGiU4u1s=
