# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 22:53
from __future__ import unicode_literals

import cms.utils
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the component', max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('is_static', models.BooleanField(default=True)),
                ('schema', models.TextField(default=False, help_text='Valid JSON Schema to validate the datatype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, help_text='(Optional) The page title is optional. If it is empty, the Page Name will be used.', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page')),
                ('site', models.ForeignKey(default=cms.utils.get_current_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'CMS Page',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Give a name for the section', max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(help_text='Select the page that this section belongs to.', on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'verbose_name': 'Page Section',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ComponentType'),
        ),
        migrations.AddField(
            model_name='component',
            name='section',
            field=models.ForeignKey(help_text='The section this component belongs to.', on_delete=django.db.models.deletion.CASCADE, to='cms.Section'),
        ),
    ]
