# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 02:37
from __future__ import unicode_literals

from django.db import migrations

def setup_base_component_type(apps, schema_editor):

    ComponentType = apps.get_model('cms', 'ComponentType')

    card = ComponentType.objects.create(name='Bootstrap Card', is_static=True, schema={
        'type': 'object',
        'properties': {
            'title': { 'type': 'string' },
            'description': { 'type': 'string' }
        }
    })


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_base_component_type)
    ]
