# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 02:37
from __future__ import unicode_literals

import json
from django.db import migrations

def setup_base_component_type(apps, schema_editor):

    ComponentType = apps.get_model('cms', 'ComponentType')

    ComponentType.objects.create(name='Bootstrap Card', is_static=True, schema=json.dumps({
        "title": "Bootstrap Card Component",
        "type": "object",
        "properties": {
            "Title": {
                "type": "string"
            },
            "Description": {
                "type": "string"
            }
        },
        "required": ["Title", "Description"]
    }))


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_base_component_type)
    ]
