# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 02:51
from __future__ import unicode_literals

import cms.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_setup-base-components'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='content',
            field=cms.fields.JSONTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cms.ComponentType'),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.CharField(blank=True, help_text="The Slug Value is auto-generated from your component's name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='slug',
            field=models.CharField(blank=True, help_text="The Slug Value is auto-generated from the component type's name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.CharField(blank=True, help_text="The Slug value is auto-generated from your section's name.", max_length=255),
        ),
    ]
