# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180312_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
