# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 01:34
from __future__ import unicode_literals

import cms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180312_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'Component Type'},
        ),
        migrations.AlterField(
            model_name='component',
            name='content',
            field=cms.fields.JSONTextField(blank=True, default='{}'),
        ),
    ]
