# Generated by Django 2.0.3 on 2018-03-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180313_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='section',
            field=models.ForeignKey(help_text='The section this component belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cms.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(help_text='Select the page that this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.Page'),
        ),
    ]
